struct CharacterData
    player_number::Bool
    hp::Int32
    energy::Int32
    x::Int32
    y::Int32
    left::Int32
    right::Int32
    top::Int32
    bottom::Int32
    speed_x::Int32
    speed_y::Int32
    state::Struct.StateEnum
    action::Struct.ActionEnum
    front::Bool
    control::Bool
    attack_data::Union{Nothing,AttackData}
    remaining_frame::Int32
    hit_confirm::Bool
    graphic_size_x::Int32
    graphic_size_y::Int32
    graphic_adjust_x::Int32
    hit_count::Int32
    last_hit_frame::Int32
    CharacterData(data) = new(
        data.player_number,
        data.hp,
        data.energy,
        data.x,
        data.y,
        data.left,
        data.right,
        data.top,
        data.bottom,
        data.speed_x,
        data.speed_y,
        Struct.StateEnum(data.state),
        Struct.ActionEnum(data.action),
        data.front,
        data.control,
        hasproperty(data, :attack_data) ? AttackData(data.attack_data) : nothing,
        data.remaining_frame,
        data.hit_confirm,
        data.graphic_size_x,
        data.graphic_size_y,
        data.graphic_adjust_x,
        data.hit_count,
        data.last_hit_frame
    )
end